import { ThemeProvider } from '@mui/material';
import '@/styles/globals.css'
import Head from 'next/head';
import theme from '@/styles/theme';

import Menu from '../components/Menu';
import { SemWebProvider } from '../state-manager/context';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta charSet="UTF-8" key="charset" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SemWebProvider>
        <ThemeProvider theme={theme}>
          <Menu></Menu>
          <Component {...pageProps} />
        </ThemeProvider>
      </SemWebProvider>
    </>
  )
}
